app:
    resource: '@AppBundle/Controller/'
    type: annotation

login_check:
  path: /login_check

logout:
  path: /logout

principal:
  path: /
  defaults: { _controller: AppBundle:Default:index }

login:
  path: /login
  defaults: { _controller: AppBundle:Default:login }

recepcionPage:
  path: /recepcionPage
  defaults: { _controller: AppBundle:Recepcion:index }

clientePage:
  path: /clientePage
  defaults: { _controller: AppBundle:Cliente:index }

#funciones de empresa

pedidosRecepcion:
  path: /pedidosRecepcion
  defaults: { _controller: AppBundle:Recepcion:pedidosRecepcion }

detallePedido:
  path: /detallePedido/{id}
  defaults: { _controller: AppBundle:Recepcion:detallePedido }

asignarSocia:
  path: /asignarSocia/{id}
  defaults: { _controller: AppBundle:Recepcion:asignarSocia }

asignacionSocia:
  path: /asignacionSocia/{id}/{id2}
  defaults:  { _controller: AppBundle:Recepcion:asignacionSocia }

completarPedido:
  path: /completarPedido/{id}
  defaults: { _controller: AppBundle:Recepcion:completarPedido }

sociasRecepcion:
  path: /sociasRecepcion
  defaults: { _controller: AppBundle:Recepcion:sociasRecepcion }

nuevaSocia:
  path: /nuevaSocia
  defaults: { _controller: AppBundle:Recepcion:nuevaSocia }

inventarioRecepcion:
  path: /inventarioRecepcion
  defaults: { _controller: AppBundle:Recepcion:inventarioRecepcion }

categoriasInventario:
  path: /categoriasInventario
  defaults: { _controller: AppBundle:Recepcion:categoriasInventario }

nuevaCategoria:
  path: /nuevaCategoria
  defaults: { _controller: AppBundle:Recepcion:nuevaCategoria }

productosInventario:
  path: /categoriasInventario
  defaults: { _controller: AppBundle:Recepcion:productosInventario }

nuevoProducto:
  path: /nuevoProducto
  defaults: { _controller: AppBundle:Recepcion:nuevoProducto }

reportesRecepcion:
  path: /reportesRecepcion
  defaults: { _controller: AppBundle:Recepcion:reportesRecepcion }

reporteFechaelegir:
  path: /reporteFechaelegir
  defaults: { _controller: AppBundle:Recepcion:reporteFechaelegir }

reporteListaclientes:
  path: /reporteListaclientes
  defaults: { _controller: AppBundle:Recepcion:reporteListaclientes }

reporteCliente:
  path: /reporteCliente/{idcliente}
  defaults: { _controller: AppBundle:Recepcion:reporteCliente }

#funciones de catalogo

catalogoProductos:
  path: /catalogoProductos
  defaults: { _controller: AppBundle:Recepcion:catalogoProductos }

#funciones del cliente

registroCliente:
  path: /registroCliente
  defaults: { _controller: AppBundle:Cliente:registroCliente }

carrito:
  path: /carrito
  defaults: { _controller: AppBundle:Cliente:carrito }

agregar:
  path: /agregar/{id}
  defaults: { _controller: AppBundle:Cliente:agregar }

quitar:
  path: /quitar/{id}
  defaults: { _controller: AppBundle:Cliente:quitar }

pedir:
  path: /pedir
  defaults: { _controller: AppBundle:Cliente:pedir }

cancelarPedido:
  path: /cancelarPedido/{id}
  defaults: { _controller: AppBundle:Cliente:cancelarPedido }



